services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-server
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:Z
      # 即使主存储在 R2，Vault 有时也需要本地空间处理临时数据
      - ./data:/vault/data:Z
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK